services:
  - type: web
    runtime: docker
    name: optibus
    branch: main
    plan: free
    region: singapore
    autoDeployTrigger: commit
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: OptiBus
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_TIMEZONE
        value: Asia/Makassar
      - key: FORCE_HTTPS
        value: "true"
      - key: TRUSTED_PROXIES
        value: "*"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_PERSISTENT
        value: "false"
      - key: DB_APPLICATION_NAME
        value: optibus-render
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
      - key: RUN_MIGRATIONS
        value: "true"
